on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go run ./internal/ci/bump/main.go
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git checkout -B ci/bump
            git add ./packages

            git commit -m "packages: Update packages to latest versions"
            git push origin ci/bump --force

            open_pr=$(gh pr list --head ci/bump --state open --json number --jq '.[0].number')
            if [[ -z "$open_pr" ]]; then
              gh pr create --base main --head ci/bump --title 'ci: Update packages to latest versions' --body ''
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
