on: pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          MODIFIED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[] | select(.additions > 0) | .path' | grep packages/ |  tr '\n' ' ')
          set -- $MODIFIED_FILES
          go run ./internal/ci/pr/main.go "$@"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
