on:
  pull_request:
  push:
    branches-ignore:
      - main
      - ci/**

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go run ./internal/ci/pr/main.go
