on: pull_request

permissions:
  contents: write

jobs:
  pr:
    strategy:
      fail-fast: true
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            os: macos-latest
          - goos: darwin
            goarch: amd64
            os: macos-latest
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: |
          MODIFIED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[] | select(.additions > 0) | .path' | grep packages/ |  tr '\n' ' ')
          set -- $MODIFIED_FILES
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go run ./internal/ci/pr/main.go "$@"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
