name: Release
on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
  release:
    strategy:
      fail-fast: false
      matrix:
        goos: [darwin, linux]
        goarch: [arm64, amd64]
        include:
          - goos: darwin
            os: macos-latest
          - goos: linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s" -o pkg
      - run: tar -acf pkg-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz pkg
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            pkg-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
