on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths:
      - packages/**
      - web/**
      - .github/workflows/web.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - run: deno install
        working-directory: web
      - run: deno run build
        working-directory: web
      - run: npx wrangler deploy
        working-directory: web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
