on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths:
      - packages/**
      - web/**

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: web
      - run: bun run build
        working-directory: web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/.vitepress/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
